import Header from './components/Header';
import Loading from './components/Loading';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				{/* <Loading/> */}
				<header className=' fixed top-0 left-0 w-full'>
					<Header />
				</header>
				<main className='mt-[8vh]'>{children}</main>
			</body>
		</html>
	);
}
